fix

diff --git a/.github/workflows/terraform_drift.yml b/.github/workflows/terraform_drift.yml
--- a/.github/workflows/terraform_drift.yml
+++ b/.github/workflows/terraform_drift.yml
@@ -22,6 +22,7 @@ jobs:
       # Step 1: Checkout the repository
       - name: Checkout the repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+
       # Step 2: Setup Terraform
       - name: Set Terraform Version
         id: env_tf_version
@@ -34,6 +35,7 @@ jobs:
         with:
           terraform_version: ${{ steps.env_tf_version.outputs.terraform_version }}
           terraform_wrapper: true
+
       # Step 3: Log in to Azure
       - name: Login to Azure
         uses: azure/login@a65d910e8af852a8061c627c456678983e180302
@@ -42,13 +44,7 @@ jobs:
           tenant-id: ${{ secrets.AZ_TENANT_ID }}
           subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
 
-      # # Step 4: List directories under /src
-      # - name: List directories under /src
-      #   run: |
-      #     echo "Listing directories under /src"
-      #     ls -d $DIR*/
-
-      # Step 5: Terraform Drift Detection for all folders under /src
+      # Step 4: Terraform Drift Detection for all folders under /src
       - name: Terraform Drift Detection for all folders under /src
         env:
           ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
@@ -65,6 +61,19 @@ jobs:
             cd $folder
 
             ./terraform.sh plan -detailed-exitcode
+
+            if [ $? -eq 0 ]; then
+              echo "No drift detected in $folder."
+            elif [ $? -eq 1 ]; then
+              echo "Terraform error in $folder."
+              exit 1  # This will cause the job to fail immediately on drift detection
+            elif [ $? -eq 2 ]; then
+              echo "Terraform drift detected in $folder."
+              exit 1  # This will cause the job to fail immediately on drift detection
+            else
+              echo "Other error in $folder."
+              exit 1  # This will cause the job to fail immediately on drift detection
+            fi
 
             # Return to the root directory before processing the next folder
             cd - || exit
