test exitcode

diff --git a/.github/workflows/terraform_drift.yml b/.github/workflows/terraform_drift.yml
--- a/.github/workflows/terraform_drift.yml
+++ b/.github/workflows/terraform_drift.yml
@@ -66,15 +66,15 @@ jobs:
         
             echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
              
-            if [ $exitcode -eq 0 ]; then
-              echo "No drift detected in $folder."
-              exit 0
+            if [ $exitcode -eq 2 ]; then
+              echo " drift detected in $folder."
+              exit 1
             elif [ $exitcode -eq 1 ]; then
               echo "Terraform error in $folder."
               exit 1  # This will cause the job to fail immediately on drift detection
-            elif [ $exitcode -eq 2 ]; then
+            elif [ $exitcode -eq 0 ]; then
               echo "Terraform drift detected in $folder."
-              exit 1  # This will cause the job to fail immediately on drift detection
+              exit 0  # This will cause the job to fail immediately on drift detection
             else
               echo "Other error in $folder."
               exit 1  # This will cause the job to fail immediately on drift detection
